### ISSUE TITLE
add some course

### ISSUE THREAD

**Issue by kof98765** [yoyo-nb/Thin-Plate-Spline-Motion-Model#10]
hi,i want to train this project,but i dont know how to download the dataset  |_| |_|,
would you help me ?

**Comment by QiFuChina** [comment]
Hi, did you find the way to download datasets? I check TaiChiHD and VoxCeleb but the website requires some accademic  certification to get so I try to create own dataset and train it. But I don't know the format about it

**Comment by machadogj** [comment]
In the readme it points to the following repository:

https://github.com/AliaksandrSiarohin/video-preprocessing

@kof98765 @QiFuChina
