### ISSUE TITLE
source image path is undefined

### ISSUE THREAD

**Issue by emmajane1313** [yoyo-nb/Thin-Plate-Spline-Motion-Model#29]
I keep getting an error of:

---> 12 source_image = imageio.imread(source_image_path)

---
the source image path however is definitely defined and correct, i have uploaded the png file directly into the assets folder and even put the path variable in line 12 "./assets/still.png" rather than calling source_image_path to double check but i still get the error

**Comment by yoyo-nb** [comment]
I guess you used google colab to run the code and forgot to run the second cell. 
The second cell will change the current running path, and only after running can the relative path be used to read the image

**Comment by emmajane1313** [comment]
just fixed it! thank you ... i think it was an error with my video path being to long and it was restarting the runtime and forgetting the path.... i get this error now "from demo import load_checkpoints" ... any ideas?

**Comment by yoyo-nb** [comment]
I don't get an error here, I still think it's due to not being in the correct run path.

Did you run `cd Thin-Plate-Spline-Motion-Model` after running `git clone`

**Comment by emmajane1313** [comment]
yeah i ran it , the solution was to restart everything again, i now get one
last error Could not find a format to write the specified file in
multi-image mode coming from > ---> 17 imageio.mimsave(output_video_path, [
img_as_ubyte(frame) for frame in predictions], fps=fps),

ValueError: Could not find a format to write the specified file in
multi-image mode

could that be some path error to? i just specified an outputs folder in the
repo i.e. "/content/Thin-Plate-Spline-Motion-Model/outputs"

sorry to bother you with all this

**Comment by yoyo-nb** [comment]
`output_video_path` should be a file path with a filename, such as `/content/Thin-Plate-Spline-Motion-Model/output.mp4`

**Comment by emmajane1313** [comment]
works thank you!
