### ISSUE TITLE
Could not find a backend to open `RESULTS`` with iomode `wI`.

### ISSUE THREAD

**Issue by cjay777xb** [yoyo-nb/Thin-Plate-Spline-Motion-Model#36]
Seems to go fine right up until the end when it's trying to open the RESULTS.MP4 file.  I've installed in Conda, pip, and Windows and it always end with that error and no RESULTS file is ever output.

(Thin-Plate-Spline) PS F:\Thin-Plate-Spline-Motion-Model> python demo.py --config config/vox-256.yaml --checkpoint checkpoints/vox.pth.tar --source_image ./assets/mfox256.jpg --driving_video ./assets/output.mp4 --result_video RESULTS --mode standard --find_best_frame
F:\Thin-Plate-Spline-Motion-Model\demo.py:147: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  source_image = imageio.imread(opt.source_image)
C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
221it [00:10, 21.03it/s]
Best frame: 115
100%|████████████████████████████████████████████████████████████████████████████████| 106/106 [00:03<00:00, 34.26it/s]
100%|████████████████████████████████████████████████████████████████████████████████| 116/116 [00:02<00:00, 43.04it/s]
Traceback (most recent call last):
  File "F:\Thin-Plate-Spline-Motion-Model\demo.py", line 178, in <module>
    imageio.mimsave(opt.result_video, [img_as_ubyte(frame) for frame in predictions], fps=fps)
  File "C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline\lib\site-packages\imageio\v2.py", line 330, in mimwrite
    with imopen(uri, "wI", **imopen_args) as file:
  File "C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline\lib\site-packages\imageio\core\imopen.py", line 303, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `RESULTS`` with iomode `wI`.
(Thin-Plate-Spline) PS F:\Thin-Plate-Spline-Motion-Model>

(Thin-Plate-Spline) PS F:\Thin-Plate-Spline-Motion-Model> conda list
# packages in environment at C:\Users\cjay777xb\.conda\envs\Thin-Plate-Spline:
#
# Name                    Version                   Build  Channel
av                        9.2.0                    pypi_0    pypi
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
blosc                     1.21.1               h74325e0_3    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge/label/cf202003
certifi                   2022.9.24        py39haa95532_0
cfitsio                   3.470                h2bbff1b_7
charls                    2.2.0                h6c2663c_0
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5                    pypi_0    pypi
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
cudatoolkit               11.6.0              hc0ea762_10    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py39hb82d6ee_0    conda-forge
dask-core                 2022.9.2           pyhd8ed1ab_0    conda-forge
ffmpeg                    4.2                  h6538335_0    conda-forge/label/cf202003
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h546665d_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.8.26        py39hc0a7faf_1
imageio                   2.22.0             pyhfa7a67d_0    conda-forge
imageio-ffmpeg            0.4.7              pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libdeflate                1.8                  h2bbff1b_5
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_4    conda-forge
libtiff                   4.4.0                h8a3f274_0
libuv                     1.44.2               h8ffe710_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.6.0                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.8.7              pyhd8ed1ab_0    conda-forge
numba                     0.56.2                   pypi_0    pypi
numpy                     1.23.2           py39h1a62c8c_0    conda-forge
opencv-python             4.6.0.66                 pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py39hcef8f5f_2    conda-forge
pip                       22.2.2           py39haa95532_0
psutil                    5.9.2                    pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hb0d2dfa_4    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.13               h6244533_1
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.12.1          py3.9_cuda11.6_cudnn8_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.3           py39h2e25243_1    conda-forge
scipy                     1.9.1                    pypi_0    pypi
setuptools                59.8.0                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sqlite                    3.39.3               h2bbff1b_0
tbb                       2021.5.0             h2d74725_1    conda-forge
tifffile                  2022.8.12                pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torchaudio                0.12.1               py39_cu116    pytorch
torchvision               0.13.1               py39_cu116    pytorch
tornado                   6.2              py39hb82d6ee_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h04d1e81_0
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
wincertstore              0.2              py39haa95532_2
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_4    conda-forge
(Thin-Plate-Spline) PS F:\Thin-Plate-Spline-Motion-Model>

**Comment by yoyo-nb** [comment]
The `result_video` parameter requires a file suffix name, such as `.mp4`.

```shell
python demo.py --config config/vox-256.yaml --checkpoint checkpoints/vox.pth.tar --source_image ./assets/mfox256.jpg --driving_video ./assets/output.mp4 --result_video RESULTS.mp4 --mode relative --find_best_frame
```

**Comment by cjay777xb** [comment]
I'm a moron....thanks!
