### ISSUE TITLE
How to crop and align the face from image and video

### ISSUE THREAD

**Issue by SwordBearFire** [yoyo-nb/Thin-Plate-Spline-Motion-Model#4]
Thank you for releasing the code, could you add the code to crop and align the face from image and video. Is it like FFHQ landmark?

Sincerely yours.

**Comment by Chopin68** [comment]
> 裁剪视频：[https ://github.com/Chando0185/first-order-model/blob/master/crop-video.py](https://github.com/Chando0185/first-order-model/blob/master/crop-video.py)
> 
> 裁剪图像：不知道，您可以将（使用 ffmpeg）图像转换为视频帧，然后使用crop-video.py 并将“min_frames”设置为0，然后将第一帧提取回图像。

Thank you. This is effective for vox model. Do you have any suggestions on the alignment and clipping of Ted model?
