### ISSUE TITLE
error when trying to train

### ISSUE THREAD

**Issue by surfingnirvana** [yoyo-nb/Thin-Plate-Spline-Motion-Model#40]
\Thin-Plate-Spline-Motion-Model\train.py", line 93, in train
    logger.log_epoch(epoch, model_save, inp=x, out=generated)
UnboundLocalError: local variable 'x' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\run.py", line 83, in <module>
    train(config, inpainting, kp_detector, bg_predictor, dense_motion_network, opt.checkpoint, log_dir, dataset)
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\train.py", line 93, in train
    logger.log_epoch(epoch, model_save, inp=x, out=generated)
TypeError: __exit__() takes 1 positional argument but 4 were given

**Comment by yoyo-nb** [comment]
It is possible that the dataset failed to load, causing [this](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/blob/main/train.py#L55) for loop not to be run.

**Comment by surfingnirvana** [comment]
The videos have mp4 format. I had the same error with the repository https://github.com/snap-research/articulated-animation/
Training articulated-animation in standard training mode with png and mp4 files was successful. When trying to train in avd mode training with mp4 did not work. pngs were working fine.
Now in thin plate model png or mp4 do not work.

**Comment by yoyo-nb** [comment]
1. you can check that the dataset path in the [config file](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/blob/main/config/vox-256.yaml#L2) is correct.
2. I use the same [dataset loading script](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/blob/main/frames_dataset.py) as [mraa](https://github.com/snap-research/articulated-animation/blob/main/frames_dataset.py) and the code should be fine
3. MRAA's avd mode uses a larger batchsize (256). mp4 mode loads a large amount of video into memory, which can lead to memory overflow, while png mode loads only two frames of images for each sample, so it is better to use PNG mode.

**Comment by surfingnirvana** [comment]
It appears to have this error when i change the num_repeats = 150 to 2 in config file.
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by yoyo-nb** [comment]
Are you using your own dataset with a small sample size, if so, change [this line](https://github.com/yoyo-nb/Thin-Plate-Spline-Motion-Model/blob/main/train.py#L43) to `drop_last=False`.

**Comment by surfingnirvana** [comment]
There is this error now. What is "staked" png exactly?


Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\frames_dataset.py", line 172, in __getitem__
    return self.dataset[idx % self.dataset.__len__()]
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\frames_dataset.py", line 133, in __getitem__
    video_array = read_video(path, frame_shape=self.frame_shape)
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\frames_dataset.py", line 40, in read_video
    video_array = video_array.reshape((-1,) + frame_shape)
TypeError: can only concatenate tuple (not "list") to tuple


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\run.py", line 83, in <module>
    train(config, inpainting, kp_detector, bg_predictor, dense_motion_network, opt.checkpoint, log_dir, dataset)
  File "C:\NEURAL\Thin-Plate-Spline-Motion-Model\train.py", line 93, in train
    logger.log_epoch(epoch, model_save, inp=x, out=generated)
TypeError: __exit__() takes 1 positional argument but 4 were given

**Comment by thhung** [comment]
@surfingnirvana Did you end up with good results from your training?
